name: weather_mobile
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  flutter_spinkit: "^4.1.2"
  location: ^3.0.0
  bloc: ^6.0.3
  http: ^0.12.2
  flutter_svg: ^0.19.0
  syncfusion_flutter_gauges: ^18.3.35
  flare_flutter: ^2.0.6
  url_launcher: ^5.7.2
  provider: ^4.3.2+2




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: googleSansRegular
      fonts:
        - asset: assets/fonts/google_sans_regular.ttf
  assets:
    - assets/svgs/location.svg
    - assets/svgs/permission.svg
    - assets/svgs/location_error.svg
    - assets/svgs/error.svg
    - assets/svgs/sun_and_cloud.svg
    - assets/svgs/sun.svg
    - assets/svgs/moon.svg
    - assets/svgs/cloud.svg
    - assets/svgs/showering.svg
    - assets/svgs/raining.svg
    - assets/svgs/thunder.svg
    - assets/svgs/snowing.svg
    - assets/svgs/wind.svg
    - assets/svgs/moon_and_cloud.svg
    - assets/flare/wind.flr

